version: "3.5"

services:
  incadevops:
    image: devops
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
    ports:
      - "12345:12345"
    environment: 
      MONGO_URI: "mongodb://mongo:27017/docker-devops"
      NODE_ENV: "development"
      JWT_SECRET: "djghhhhuuwiwuewieuwieuricc"
      JWT_LOGIN_EXPIRED_IN: "1d"
      JWT_REGISTER_EXPIRED_IN: "30d"
      JWT_REFRESHTOKEN_EXPIRED-IN: "1h"
      NOTIFICATION_TIME_POLLING: 30000
      NOTIFICATION_ACTIVATE_WEB_SOCKET: "disable"
      REGISTRY_URL: "http://sndregistry.sondeosglobal.com:8080/v2/"
      APP_NAME:  "INCADEVOPS"
      APP_PORT: 12345
      APP_API_URL: "http://localhost:12345"
      MEDIA_DEFAULT_CAPACITY: 1024
      MEDIA_MAX_SIZE_PER_FILE_IN_MEGABYTES: 4096
      MEDIA_FILE_EXPIRATION_TIME_IN_DAYS: 180
      MEDIA_DELETE_FILES_CRON: "0 0 0 * * * *"
      SMTP_HOST: "smtp.equila.com.ar"
      SMTP_PORT: 25
      SMTP_SECURE: "false"
      SMTP_USER: "pruebas@impakto.com.ar"
      SMTP_PASS: "Pru.3135!"
      LOG_LEVEL: "debug"
      LOG_REQUEST: "ON"
      LOG_RESPONSE_TIME: "ON"
      LOG_GQL_ERRORS: "ON"
      LOG_TRANSPORT_CONSOLE: "ON"
      LOG_TRANSPORT_COMBINED: "ON"
      LOG_TRANSPORT_ERROR: "ON"
      LOG_TRANSPORT_ACCESS: "ON"
      LOG_TRANSPORT_GQL_ERROR: "ON"
      LOG_TRANSPORT_GQL_RESPONSE: "ON"
      LOG_COLORIZE: "ON"
      LOG_FILE_MAX_SIZE: 10000000
      LOG_FILE_MAX_FILES: 3
      LOG_MODE: "TEXT"
    deploy:
      mode: replicated
      replicas: 1