
export const REGISTRY_MENU = "REGISTRY_MENU"
export const REGISTRY_SHOW = "REGISTRY_SHOW"
export const REGISTRY_UPDATE = "REGISTRY_UPDATE"
export const REGISTRY_CREATE = "REGISTRY_CREATE"
export const REGISTRY_DELETE = "REGISTRY_DELETE"
    