
export const ENVIRONMENT_MENU = "ENVIRONMENT_MENU"
export const ENVIRONMENT_SHOW = "ENVIRONMENT_SHOW"
export const ENVIRONMENT_UPDATE = "ENVIRONMENT_UPDATE"
export const ENVIRONMENT_CREATE = "ENVIRONMENT_CREATE"
export const ENVIRONMENT_DELETE = "ENVIRONMENT_DELETE"
    