
export const ENVIRONMENTSERVICE_MENU = "ENVIRONMENTSERVICE_MENU"
export const ENVIRONMENTSERVICE_SHOW = "ENVIRONMENTSERVICE_SHOW"
export const ENVIRONMENTSERVICE_UPDATE = "ENVIRONMENTSERVICE_UPDATE"
export const ENVIRONMENTSERVICE_CREATE = "ENVIRONMENTSERVICE_CREATE"
export const ENVIRONMENTSERVICE_DELETE = "ENVIRONMENTSERVICE_DELETE"
    