
export const ENVIRONMENT_MENU = "ENVIRONMENT_MENU"
export const ENVIRONMENT_SHOW = "ENVIRONMENT_SHOW"
export const ENVIRONMENT_UPDATE = "ENVIRONMENT_UPDATE"
export const ENVIRONMENT_CREATE = "ENVIRONMENT_CREATE"
export const ENVIRONMENT_DELETE = "ENVIRONMENT_DELETE"

export const DEV_VIEW = "DEV_VIEW"
export const DEV_EDIT = "DEV_EDIT"
export const DEV_ENV = "DEV_ENV"
export const DEV_DEPLOY = "DEV_DEPLOY"
export const DEV_DELETE = "DEV_DELETE"
export const QA_VIEW = "QA_VIEW"
export const QA_EDIT = "QA_EDIT"
export const QA_ENV = "QA_ENV"
export const QA_DEPLOY = "QA_DEPLOY"
export const QA_DELETE = "QA_DELETE"
export const PRE_VIEW = "PRE_VIEW"
export const PRE_DELETE = "PRE_DELETE"
export const PRE_EDIT = "PRE_EDIT"
export const PRE_ENV = "PRE_ENV"
export const PRE_DEPLOY = "PRE_DEPLOY"
export const PROD_VIEW = "PROD_VIEW"
export const PROD_EDIT = "PROD_EDIT"
export const PROD_ENV = "PROD_ENV"
export const PROD_DEPLOY = "PROD_DEPLOY"
export const PROD_DELETE = "PROD_DELETE"