
export const PLATFORM_MENU = "PLATFORM_MENU"
export const PLATFORM_SHOW = "PLATFORM_SHOW"
export const PLATFORM_UPDATE = "PLATFORM_UPDATE"
export const PLATFORM_CREATE = "PLATFORM_CREATE"
export const PLATFORM_DELETE = "PLATFORM_DELETE"
    