
export const SERVICE_TEMPLATE_MENU = "SERVICE_TEMPLATE_MENU"
export const SERVICE_TEMPLATE_SHOW = "SERVICE_TEMPLATE_SHOW"
export const SERVICE_TEMPLATE_UPDATE = "SERVICE_TEMPLATE_UPDATE"
export const SERVICE_TEMPLATE_CREATE = "SERVICE_TEMPLATE_CREATE"
export const SERVICE_TEMPLATE_DELETE = "SERVICE_TEMPLATE_DELETE"
    