
export const SERVICE_MENU = "SERVICE_MENU"
export const SERVICE_SHOW = "SERVICE_SHOW"
export const SERVICE_UPDATE = "SERVICE_UPDATE"
export const SERVICE_CREATE = "SERVICE_CREATE"
export const SERVICE_DELETE = "SERVICE_DELETE"
    